### ISSUE TITLE
Compatibility with Flow

### ISSUE THREAD

**Issue by Ricy40** [ConorTheDev/LyricifyBugTracker#16]
Not much of a bug but could you attempt to add compatibility with the flow tweak. They would look awese together. Along tweak tho, cheers :)

**Comment by ConorTheDev** [comment]
Just added on development, will be released with v1.1

**Comment by Ricy40** [comment]
Cool thank you so much!!! Can't wait!!

Sent from my iPhone

On Feb 4, 2020, at 4:53 PM, Conor <notifications@github.com> wrote:

﻿

Just added on development, will be released with v1.1
