### ISSUE TITLE
Love the tweak, but any chance you can make it compatible with Sylph?

### ISSUE THREAD

**Issue by Hazard719** [ConorTheDev/LyricifyBugTracker#7]
![E25090EE-9E2E-45D2-BCAD-0DC37F3BF51C](https://user-images.githubusercontent.com/59908206/72409426-5789ee00-372b-11ea-9ff9-42a496c0ed21.png)
It works just fine, but the button for lyrics is on top of the arrow for next track. There is a very small space in the corner of the button that actually registers me tapping next. Again love the tweak and many thanks!

**Comment by ConorTheDev** [comment]
That’s being worked on at the moment

**Comment by ConorTheDev** [comment]
Will be added in v1.1
