### ISSUE TITLE
(ios 12.1.1) springboard crash

### ISSUE THREAD

**Issue by kevindery** [ConorTheDev/LyricifyBugTracker#8]
Hi i have a crash each time it is installed, i've got the full logs if you need them.
Device: iPhone 6s Plus, iOS 12.1.1
{"ProcessBundleID":"com.apple.springboard","ProcessName":"SpringBoard","Culprit":"Lyricify.dylib"}

EDIT:
Was watching others topics and it seem to be the vm protection too.
Exception type: EXC_BAD_ACCESS (SIGSEGV)
Exception subtype: KERN_INVALID_ADDRESS: 0x0
Exception codes: 0x0000000000000001, 0x0000000000000000
Culprit: Lyricify.dylib
VM Protection: 0x0 is not in any region.

**Comment by ConorTheDev** [comment]
If you could send the full crash log that would be helpful

**Comment by kevindery** [comment]
https://pastebin.com/kZLx6r4k

**Comment by ConorTheDev** [comment]
Duplicate of #12
